[project]
name = "llm-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.0",
    "jupyterlab>=4.0.0",
    "numpy>=2.3.2",
    "requests>=2.32.4",
]
